In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size = 10000

In [27]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[39, 919, 1785, 8434],
 [39, 919, 1785, 5932],
 [39, 3109, 1785, 9169],
 [7920, 396, 4379, 6928, 5308],
 [7920, 396, 4379, 6928, 3141],
 [1082, 39, 778, 1785, 1559],
 [7577, 9378, 4192, 6928]]

In [28]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [29]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0   39  919 1785 8434]
 [   0    0    0    0   39  919 1785 5932]
 [   0    0    0    0   39 3109 1785 9169]
 [   0    0    0 7920  396 4379 6928 5308]
 [   0    0    0 7920  396 4379 6928 3141]
 [   0    0    0 1082   39  778 1785 1559]
 [   0    0    0    0 7577 9378 4192 6928]]


In [30]:
## feature representation
dim=10

In [31]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Projects\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [32]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step


array([[[ 0.01722952,  0.0308772 , -0.0245393 , -0.03439531,
         -0.04101207,  0.03038101,  0.01769413,  0.03655108,
          0.028435  ,  0.04687509],
        [ 0.01722952,  0.0308772 , -0.0245393 , -0.03439531,
         -0.04101207,  0.03038101,  0.01769413,  0.03655108,
          0.028435  ,  0.04687509],
        [ 0.01722952,  0.0308772 , -0.0245393 , -0.03439531,
         -0.04101207,  0.03038101,  0.01769413,  0.03655108,
          0.028435  ,  0.04687509],
        [ 0.01722952,  0.0308772 , -0.0245393 , -0.03439531,
         -0.04101207,  0.03038101,  0.01769413,  0.03655108,
          0.028435  ,  0.04687509],
        [ 0.02419973, -0.03886461,  0.03423426,  0.04403427,
          0.02148681, -0.02870401, -0.03340542, -0.0403287 ,
         -0.02154787,  0.03618269],
        [ 0.04870775,  0.01186174,  0.04187726,  0.02586957,
         -0.04066154,  0.03994668, -0.00338602, -0.04499118,
         -0.0295081 ,  0.00249986],
        [ 0.03920634, -0.0379683 , -0.02222195, -0.0

In [34]:
embedded_docs[0]

array([   0,    0,    0,    0,   39,  919, 1785, 8434])

In [35]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None